'ascii' codec can't encode character u'\xe9' in position 4: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 122, in view_results
    filter_form=_filter_form)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/templates/search_results.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/templates/base.html", line 298, in top-level template code
    {% block content %}
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/templates/search_results.html", line 75, in block "content"
    {{ filter_form[_form_names.name_province](
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/wtforms/fields/core.py", line 153, in __call__
    return self.meta.render_field(self, kwargs)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/wtforms/meta.py", line 56, in render_field
    return field.widget(field, **render_kw)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/wtforms/widgets/core.py", line 288, in __call__
    html.append(self.render_option(val, label, selected))
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/hack.py", line 140, in render_option
    selected = coerce_func(value) == data
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 4: ordinal not in range(128)
'ascii' codec can't encode character u'\xe9' in position 4: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 122, in view_results
    filter_form=_filter_form)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/templates/search_results.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/templates/base.html", line 298, in top-level template code
    {% block content %}
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/templates/search_results.html", line 75, in block "content"
    {{ filter_form[_form_names.name_province](
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/wtforms/fields/core.py", line 153, in __call__
    return self.meta.render_field(self, kwargs)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/wtforms/meta.py", line 56, in render_field
    return field.widget(field, **render_kw)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/wtforms/widgets/core.py", line 288, in __call__
    html.append(self.render_option(val, label, selected))
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/hack.py", line 140, in render_option
    selected = coerce_func(value) == data
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 4: ordinal not in range(128)
decoding Unicode is not supported
Traceback (most recent call last):
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 48, in index
    return render_template('landing_page.html', _fields=b_c, form=form)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/templates/landing_page.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/templates/base.html", line 159, in top-level template code
    {{ forms['advanced'][_form_names.name_province](
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/wtforms/fields/core.py", line 153, in __call__
    return self.meta.render_field(self, kwargs)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/wtforms/meta.py", line 56, in render_field
    return field.widget(field, **render_kw)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/wtforms/widgets/core.py", line 288, in __call__
    html.append(self.render_option(val, label, selected))
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/hack.py", line 140, in render_option
    selected = unicode(value, 'utf8') == data
TypeError: decoding Unicode is not supported
unknown encoding: uft-8
Traceback (most recent call last):
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 48, in index
    return render_template('landing_page.html', _fields=b_c, form=form)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/templates/landing_page.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/templates/base.html", line 159, in top-level template code
    {{ forms['advanced'][_form_names.name_province](
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/wtforms/fields/core.py", line 153, in __call__
    return self.meta.render_field(self, kwargs)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/wtforms/meta.py", line 56, in render_field
    return field.widget(field, **render_kw)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/wtforms/widgets/core.py", line 288, in __call__
    html.append(self.render_option(val, label, selected))
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/hack.py", line 139, in render_option
    value = value.decode('uft-8')
LookupError: unknown encoding: uft-8
'long' object has no attribute 'decode'
Traceback (most recent call last):
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 122, in view_results
    filter_form=_filter_form)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/templates/search_results.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/templates/base.html", line 298, in top-level template code
    {% block content %}
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/templates/search_results.html", line 63, in block "content"
    {{ filter_form[_form_names.name_provider](
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/wtforms/fields/core.py", line 153, in __call__
    return self.meta.render_field(self, kwargs)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/wtforms/meta.py", line 56, in render_field
    return field.widget(field, **render_kw)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/wtforms/widgets/core.py", line 288, in __call__
    html.append(self.render_option(val, label, selected))
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/hack.py", line 139, in render_option
    value = value.decode('utf-8')
AttributeError: 'long' object has no attribute 'decode'
'int' object has no attribute 'decode'
Traceback (most recent call last):
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 122, in view_results
    filter_form=_filter_form)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/templates/search_results.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/templates/base.html", line 298, in top-level template code
    {% block content %}
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/templates/search_results.html", line 63, in block "content"
    {{ filter_form[_form_names.name_provider](
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/wtforms/fields/core.py", line 153, in __call__
    return self.meta.render_field(self, kwargs)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/wtforms/meta.py", line 56, in render_field
    return field.widget(field, **render_kw)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/wtforms/widgets/core.py", line 288, in __call__
    html.append(self.render_option(val, label, selected))
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/hack.py", line 140, in render_option
    selected = coerce_func(value).decode('utf8') == data
AttributeError: 'int' object has no attribute 'decode'
'int' object has no attribute 'decode'
Traceback (most recent call last):
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 122, in view_results
    filter_form=_filter_form)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/templates/search_results.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/templates/base.html", line 298, in top-level template code
    {% block content %}
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/templates/search_results.html", line 63, in block "content"
    {{ filter_form[_form_names.name_provider](
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/wtforms/fields/core.py", line 153, in __call__
    return self.meta.render_field(self, kwargs)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/wtforms/meta.py", line 56, in render_field
    return field.widget(field, **render_kw)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/wtforms/widgets/core.py", line 288, in __call__
    html.append(self.render_option(val, label, selected))
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/hack.py", line 140, in render_option
    selected = coerce_func(value).decode('utf8') == data
AttributeError: 'int' object has no attribute 'decode'
'int' object has no attribute 'decode'
Traceback (most recent call last):
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 122, in view_results
    filter_form=_filter_form)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/templates/search_results.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/templates/base.html", line 298, in top-level template code
    {% block content %}
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/templates/search_results.html", line 63, in block "content"
    {{ filter_form[_form_names.name_provider](
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/wtforms/fields/core.py", line 153, in __call__
    return self.meta.render_field(self, kwargs)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/wtforms/meta.py", line 56, in render_field
    return field.widget(field, **render_kw)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/wtforms/widgets/core.py", line 288, in __call__
    html.append(self.render_option(val, label, selected))
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/hack.py", line 140, in render_option
    selected = coerce_func(value).decode('utf8') == data
AttributeError: 'int' object has no attribute 'decode'
year=1893 is before 1900; the datetime strftime() methods require year >= 1900
Traceback (most recent call last):
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 273, in download_csv
    _csv_content = service.get_csv_for_fields(scientific_name=_scientific_name)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 222, in get_csv_for_fields
    w.writerows([collection.as_dict for collection in collection_filter])
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/sqlalchemy/ext/hybrid.py", line 744, in __get__
    return self.fget(instance)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/models.py", line 114, in as_dict
    (gettext('header.last_date'), self.last_date.strftime(c.general_date_format) if self.last_date else ''),
ValueError: year=1893 is before 1900; the datetime strftime() methods require year >= 1900
'NoneType' object has no attribute 'day'
Traceback (most recent call last):
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 273, in download_csv
    _csv_content = service.get_csv_for_fields(scientific_name=_scientific_name)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 222, in get_csv_for_fields
    w.writerows([collection.as_dict for collection in collection_filter])
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/sqlalchemy/ext/hybrid.py", line 744, in __get__
    return self.fget(instance)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/models.py", line 114, in as_dict
    (gettext('header.last_date'), '{0.day:{1}}/{0.month:{1}}/{0.year}'.format(self.last_date, '02')),
AttributeError: 'NoneType' object has no attribute 'day'
need more than 0 values to unpack
Traceback (most recent call last):
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 273, in download_csv
    _csv_content = service.get_csv_for_fields(scientific_name=_scientific_name)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 222, in get_csv_for_fields
    w.writerows([collection.as_dict for collection in collection_filter])
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/sqlalchemy/ext/hybrid.py", line 744, in __get__
    return self.fget(instance)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/models.py", line 114, in as_dict
    (gettext('header.last_date'), '{0.day:{1}}/{0.month:{1}}/{0.year}'.format(self.last_date, '02')) if self.last_date else '',
  File "/usr/lib64/python2.7/collections.py", line 69, in __init__
    self.__update(*args, **kwds)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/_abcoll.py", line 571, in update
    for key, value in other:
ValueError: need more than 0 values to unpack
No row was found for one()
Traceback (most recent call last):
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 48, in index
    return render_template('landing_page.html', _fields=b_c, form=form)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/templating.py", line 132, in render_template
    ctx.app.update_template_context(context)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 764, in update_template_context
    context.update(func())
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 509, in inject_portal_data
    _data = service.get_portal_data(),
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 26, in get_portal_data
    stakeholders = self.get_stacke_holders_images()
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 65, in get_stacke_holders_images
    ('logo_url_uem', self.get_image('logo_uem', c.CODE_IMG_LOGO, height=80)),
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 41, in get_image
    multimedia = Multimedia.query.filter(Multimedia.short_name == short_name, Multimedia.type == image_type).one()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2820, in one
    raise orm_exc.NoResultFound("No row was found for one()")
NoResultFound: No row was found for one()
No row was found for one()
Traceback (most recent call last):
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 48, in index
    return render_template('landing_page.html', _fields=b_c, form=form)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/templating.py", line 132, in render_template
    ctx.app.update_template_context(context)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 764, in update_template_context
    context.update(func())
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 509, in inject_portal_data
    _data = service.get_portal_data(),
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 26, in get_portal_data
    stakeholders = self.get_stacke_holders_images()
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 69, in get_stacke_holders_images
    ('logo_url_cbt', self.get_image('logo_cb', c.CODE_IMG_LOGO)),
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 41, in get_image
    multimedia = Multimedia.query.filter(Multimedia.short_name == short_name, Multimedia.type == image_type).one()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2820, in one
    raise orm_exc.NoResultFound("No row was found for one()")
NoResultFound: No row was found for one()
No row was found for one()
Traceback (most recent call last):
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 48, in index
    return render_template('landing_page.html', _fields=b_c, form=form)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/templating.py", line 132, in render_template
    ctx.app.update_template_context(context)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 764, in update_template_context
    context.update(func())
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 509, in inject_portal_data
    _data = service.get_portal_data(),
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 26, in get_portal_data
    stakeholders = self.get_stacke_holders_images()
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 69, in get_stacke_holders_images
    ('logo_url_cbt', self.get_image('logo_cb', c.CODE_IMG_LOGO)),
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 41, in get_image
    multimedia = Multimedia.query.filter(Multimedia.short_name == short_name, Multimedia.type == image_type).one()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2820, in one
    raise orm_exc.NoResultFound("No row was found for one()")
NoResultFound: No row was found for one()
No row was found for one()
Traceback (most recent call last):
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 48, in index
    return render_template('landing_page.html', _fields=b_c, form=form)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/templating.py", line 132, in render_template
    ctx.app.update_template_context(context)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 764, in update_template_context
    context.update(func())
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 509, in inject_portal_data
    _data = service.get_portal_data(),
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 26, in get_portal_data
    stakeholders = self.get_stacke_holders_images()
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 69, in get_stacke_holders_images
    ('logo_url_cbt', self.get_image('logo_cb', c.CODE_IMG_LOGO)),
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 41, in get_image
    multimedia = Multimedia.query.filter(Multimedia.short_name == short_name, Multimedia.type == image_type).one()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2820, in one
    raise orm_exc.NoResultFound("No row was found for one()")
NoResultFound: No row was found for one()
No row was found for one()
Traceback (most recent call last):
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 48, in index
    return render_template('landing_page.html', _fields=b_c, form=form)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/templating.py", line 132, in render_template
    ctx.app.update_template_context(context)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 764, in update_template_context
    context.update(func())
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 509, in inject_portal_data
    _data = service.get_portal_data(),
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 26, in get_portal_data
    stakeholders = self.get_stacke_holders_images()
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 69, in get_stacke_holders_images
    ('logo_url_cbt', self.get_image('logo_cb', c.CODE_IMG_LOGO)),
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 41, in get_image
    multimedia = Multimedia.query.filter(Multimedia.short_name == short_name, Multimedia.type == image_type).one()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2820, in one
    raise orm_exc.NoResultFound("No row was found for one()")
NoResultFound: No row was found for one()
No row was found for one()
Traceback (most recent call last):
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 48, in index
    return render_template('landing_page.html', _fields=b_c, form=form)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/templating.py", line 132, in render_template
    ctx.app.update_template_context(context)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 764, in update_template_context
    context.update(func())
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 509, in inject_portal_data
    _data = service.get_portal_data(),
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 26, in get_portal_data
    stakeholders = self.get_stacke_holders_images()
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 69, in get_stacke_holders_images
    ('logo_url_cbt', self.get_image('logo_cb', c.CODE_IMG_LOGO)),
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 41, in get_image
    multimedia = Multimedia.query.filter(Multimedia.short_name == short_name, Multimedia.type == image_type).one()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2820, in one
    raise orm_exc.NoResultFound("No row was found for one()")
NoResultFound: No row was found for one()
No row was found for one()
Traceback (most recent call last):
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 48, in index
    return render_template('landing_page.html', _fields=b_c, form=form)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/templating.py", line 132, in render_template
    ctx.app.update_template_context(context)
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/flask/app.py", line 764, in update_template_context
    context.update(func())
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/view.py", line 509, in inject_portal_data
    _data = service.get_portal_data(),
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 26, in get_portal_data
    stakeholders = self.get_stacke_holders_images()
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 69, in get_stacke_holders_images
    ('logo_url_cbt', self.get_image('logo_cb', c.CODE_IMG_LOGO)),
  File "/home/silvino/dev/python/srcs/bionomo/bionomo_pilot/service/bionomo_service.py", line 41, in get_image
    multimedia = Multimedia.query.filter(Multimedia.short_name == short_name, Multimedia.type == image_type).one()
  File "/home/silvino/dev/python/envs/bionomo_pilot/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2820, in one
    raise orm_exc.NoResultFound("No row was found for one()")
NoResultFound: No row was found for one()
